app:
  name: "memebot-go"
  env: "dev"
  metrics_addr: ":9090"
  log_level: "info"

exchange:
  name: "binance" # provider for realtime market data feed
  symbols: ["BTCUSDT", "ETHUSDT"]
  api_key: ""
  api_secret: ""
  testnet: true

risk:
  max_notional_per_trade: 50.0
  max_daily_loss: 200.0
  kill_switch_drawdown: 0.08

strategy:
  mode: "obi_momentum" # order book imbalance + momentum
  params:
    obi_levels: 5
    obi_threshold: 1.4
    vol_window_secs: 120

dex:
  chain: "solana"
  rpc_url: "https://api.mainnet-beta.solana.com"
  commitment: "confirmed"
  jupiter_base: "https://quote-api.jup.ag"

wallet:
  private_key_base58: "" # kept empty; we load from .env at runtime

paper:
  starting_cash: 10000
  max_position_per_symbol: 1.0
  slippage_bps: 5
  max_latency_ms: 150
  partial_fill_probability: 0.4
  max_partial_fills: 3
  fills_path: "paper_fills.jsonl"

